sudo: false
language: python
python:
- 2.7
- 3.6
script: python -m compileall src/
deploy:
  provider: pypi
  on:
    tags: true
    all_branches: true
  user: traylenator
  password:
    secure: FqWQnRSKlMC6Eu2IjyJ0IgApA76tVkSBkjdSAv4QueIWtnQKM9gwJPuyTu6N9C4LJpLZZ82FrTSASEUlzjMsHKeEQCF4b4XhTW5Qepf07oqEqHMnZG6LlDaXORVAWQuUDQqGE4eZJSft79AppiYXa8W5ZUG0daTtQ2EhTpQKGnlQd+HfzZ4fTd589ajBL2osCF8aqVdVaF9r3wzIeTXVBXdBmI82ggR1CI4wisZMJ0/ldQb+KeV15pQbR4SiiKIPO7OCoOe5oN1qOe7h+8Zije+TrI6Bbnb8dGmUSPgE5UL00Ehd90L2WK+XancJ+F+dpaK9FkCe5yolvxvWFxaAwDRRtMbsPq+PMUq1638zrE0yOUClQ+Q2LBwRjmy6XHIoLN/V7lZS0PnQzYCj2Mt3Zwnm4MJryZfvbyqjJqbugxvpx9Wpd7Ob3teMylCHNg6niHu1cVYG41mw9GrydSEsv0D/za2foOhx/9dD9nsQdcnY4b6j/ub7CHSvG/7/HoJqmWgyupW2+cunQR8mqKfiw487Ymyo3hInwYGrP/ki6x4zsuOHsovLPPBs06ICFkT+3b7bp4DoGcozywe8fJtvdR2lz+im+ib/hFnb2HcsMiSNUsXqSf+twNaNuKSy17XJMVT1e4VEQGqHWYlOdKyMUeEqA5VSMnzUzhNe8f1dtFY=
