# .github/workflows/ci.yml
name: CI
on:
  push:
  pull_request:

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.6", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        include:
          # Older CPythons live on Debian Buster images
          - python: "3.6"
            image: "python:3.6-buster"
          # Current releases use Debian Bookworm images
          - python: "3.9"
            image: "python:3.9-bookworm"
          - python: "3.10"
            image: "python:3.10-bookworm"
          - python: "3.11"
            image: "python:3.11-bookworm"
          - python: "3.12"
            image: "python:3.12-bookworm"
          - python: "3.13"
            image: "python:3.13-bookworm"
          - python: "3.14"
            image: "python:3.14-rc-bookworm"

    # Run each matrix entry *inside* the chosen Python image
    container:
      image: ${{ matrix.image }}

    steps:
      - uses: actions/checkout@v4

      # Cache pip inside the container filesystem
      - name: Set up pip cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python }}-${{ hashFiles('**/pyproject.toml', '**/requirements*.txt', 'tox.ini', 'setup.cfg', 'setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python }}-

      - name: Show Python
        run: python -V && which python && pip -V

      - name: Upgrade pip & install tox
        run: |
            python -m pip install --upgrade pip
            pip install tox

      - name: Run tox for current interpreter
        run: tox -e py

